In [1]:
import pandas as pd
fileinput = 'wos-complete.csv'
df = pd.read_csv(fileinput, sep=';')

In [2]:
df.iloc[37, 0:]['Document Type']

'Proceedings Paper'

In [3]:
df[df['Publication Year'].isnull()]["Early Access Date"]
df[df['Publication Year'].isnull()]['Publication Year']

6   NaN
Name: Publication Year, dtype: float64

In [4]:
from dateutil.parser import parse
df.loc[df['Publication Year'].isnull(), 'Publication Year'] = df.loc[df['Publication Year'].isnull(), 'Early Access Date'].apply(lambda x: parse(x, fuzzy=True).year)

In [5]:
df['Publication Year'] = df['Publication Year'].astype(int)

In [6]:
df['Document Type'] = df['Document Type'].replace(['Article; Early Access'], 'Article')

In [7]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df.loc[df['Document Type'] == "Review"])

Empty DataFrame
Columns: [Publication Type, Authors, Book Authors, Book Editors, Book Group Authors, Author Full Names, Book Author Full Names, Group Authors, Article Title, Source Title, Book Series Title, Book Series Subtitle, Language, Document Type, Conference Title, Conference Date, Conference Location, Conference Sponsor, Conference Host, Author Keywords, Keywords Plus, Abstract, Addresses, Reprint Addresses, Email Addresses, Researcher Ids, ORCIDs, Funding Orgs, Funding Text, Cited References, Cited Reference Count, Times Cited, WoS Core, Times Cited, All Databases, 180 Day Usage Count, Since 2013 Usage Count, Publisher, Publisher City, Publisher Address, ISSN, eISSN, ISBN, Journal Abbreviation, Journal ISO Abbreviation, Publication Date, Publication Year, Volume, Issue, Part Number, Supplement, Special Issue, Meeting Abstract, Start Page, End Page, Article Number, DOI, Book DOI, Early Access Date, Number of Pages, WoS Categories, Research Areas, IDS Number, UT (Unique WOS ID), Pubmed Id, Open Access Designations, Highly Cited Status, Hot Paper Status, Date of Export, Unnamed: 67]
Index: []

In [8]:
# Type of publication to CSV file

res = df.groupby(['Publication Year','Document Type'],dropna=False).size().to_frame('count').sort_values(by=['Publication Year']).reset_index()
res.to_csv('publication-year-type.csv', sep=',', index=True, index_label='X')
res

    Publication Year      Document Type  count
0               2016  Proceedings Paper      1
1               2018            Article      1
2               2018          Pre-print      2
3               2018  Proceedings Paper      9
4               2019  Proceedings Paper      8
5               2020            Article      3
6               2020          Pre-print      1
7               2020  Proceedings Paper      8
8               2021            Article      4
9               2021          Pre-print      1
10              2021  Proceedings Paper      2

In [9]:
#df.replace(to_replace='Proceedings Paper', value='Confrence Proceeding', inplace=True)

In [10]:
# Year of publication to CSV file

res = df.groupby(['Publication Year'], dropna=False).size().to_frame('count').sort_values(by=['Publication Year'])
res.to_csv('publication-year.csv', sep=',')
res

                  count
Publication Year
2016                  1
2018                 12
2019                  8
2020                 12
2021                  7

In [11]:
# Year of publication to CSV file

res = df.groupby(['Document Type'], dropna=False).size().to_frame('count').sort_values(by=['Document Type'])
res.to_csv('publication-type.csv', sep=',')
res

                   count
Document Type
Article                8
Pre-print              4
Proceedings Paper     28

In [13]:
df.groupby(['Publication Year', 'Document Type'], dropna=False).size().to_frame('count').sort_values(by=['Document Type'])

                                    count
Publication Year Document Type
2018             Article                1
2020             Article                3
2021             Article                4
2018             Pre-print              2
2020             Pre-print              1
2021             Pre-print              1
2016             Proceedings Paper      1
2018             Proceedings Paper      9
2019             Proceedings Paper      8
2020             Proceedings Paper      8
2021             Proceedings Paper      2

In [14]:
# Year of publication to CSV file
res = df.groupby(['Publication Year', 'Document Type'], dropna=False).size().to_frame('count').sort_values(by=['Document Type'])
res = res.reset_index().pivot(index='Publication Year', columns='Document Type', values='count').fillna(0).astype(int)

res.to_csv('publication-all.csv', sep=',')
res

Document Type     Article  Pre-print  Proceedings Paper
Publication Year
2016                    0          0                  1
2018                    1          2                  9
2019                    0          0                  8
2020                    3          1                  8
2021                    4          1                  2